[package]
name = "openblas"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
build = "build.rs"

[lib]
name = "openblas"
path = "src/lib.rs"

[build-dependencies]
walkdir = "^1"

[dependencies]
libc = "*"
